Root cause in triggering tests:
 - com.google.javascript.jscomp.CommandLineRunnerTest::testSimpleModeLeavesUnusedParams
   --> junit.framework.AssertionFailedError: 
 - com.google.javascript.jscomp.CommandLineRunnerTest::testForwardDeclareDroppedTypes
   --> junit.framework.AssertionFailedError: 
 - com.google.javascript.jscomp.CommandLineRunnerTest::testDebugFlag1
   --> junit.framework.AssertionFailedError: 
 - com.google.javascript.jscomp.IntegrationTest::testIssue787
   --> junit.framework.AssertionFailedError: 
 - com.google.javascript.jscomp.RemoveUnusedVarsTest::testRemoveGlobal1
   --> junit.framework.AssertionFailedError: 
 - com.google.javascript.jscomp.RemoveUnusedVarsTest::testRemoveGlobal2
   --> junit.framework.AssertionFailedError: 
 - com.google.javascript.jscomp.RemoveUnusedVarsTest::testRemoveGlobal3
   --> junit.framework.AssertionFailedError: 
 - com.google.javascript.jscomp.RemoveUnusedVarsTest::testIssue168b
   --> junit.framework.AssertionFailedError: 
--------------------------------------------------------------------------------
List of modified sources:
 - com.google.javascript.jscomp.RemoveUnusedVars
--------------------------------------------------------------------------------
